### ISSUE TITLE
Add resourcePrefix to prevent resource naming clashes

### ISSUE THREAD

**Issue by Numan1617** [OceanLabs/Android-Print-SDK#162]
When using the library your resources can potentially override those of our app.

E.g. if we have a string called `Total` in our app resources but have yet to translate it into French then our app is forced to use the string defined by your SDK.

This behaviour is not ideal as we may want to have the French change to the default language of our app and this should ideally not be affected by using your library.

I'd suggest using resourcePrefix in the SDK's build.gradle:
```
android {
  resourcePrefix 'kitesdk_'
}
```

This will flag up errors on any resources that are yet to conform to the above prefix so they can be standardised within your SDK.

More info on resource prefix:
- [Build tools 0.10.0](http://tools.android.com/tech-docs/new-build-system)
- [Android Studio 0.5.8](http://tools.android.com/recent/androidstudio058released)

**Comment by JLKite** [comment]
Hi James,

Thank you for your message. I notice from your profile that you now work 
for Lifecake, and I am curious as to why, given that Lifecake seem to be 
responsible for maintaining and supplying all our translations, you 
would want to not use them?

Maybe I misunderstand what you want to do, but if you changed the 
default language (or had different versions of the app with different 
default languages), wouldn't there need to be matching SDKs for each 
default language? Can't you simply override the SDK resources with your 
own versions?

I can see a benefit to separating resources into essentially different 
namespaces, using the prefixes, but only if you want to re-use ids in 
different contexts, for different purposes. It seems that it would be a 
lot of work, and you're the only person who's asked for it. Also, how 
would we support customers who are actually using those resources currently?

Incidentally, there's a Slack channel for Kite - Lifecake conversations. 
I'm not sure who on your side you need to speak to about getting access. 
Maybe Pauline?

Regards,

John

**Comment by Numan1617** [comment]
Hi John,

This was totally unrelated to Lifecake and was more of a heads up to help you improve your library for your current and future customers and generally make a better product.  Basically one developer trying to help out another which is what open source is all about. I opened the issue to have the conversation to see your thoughts and potentially open a pull request if you were amicable with the idea.

It really is beneficial to people using your library to not be affected by clashes in naming.

> Can't you simply override the SDK resources with your own versions?
Yes a developer using your library could potentially override every string that clashes with yours however there may be business cases where they don't want to or simply are happy to use the default language.

> I can see a benefit to separating resources into essentially different namespaces, using the prefixes, but only if you want to re-use ids in different contexts
The problem is that your strings aren't using ID's that have a full context that will match every other context. E.g. you have a very generically named string with the ID `Description` which for you is just the word description, but in the context of another app this could be VERY different.

> Also, how would we support customers who are actually using those resources currently?
This could easily be handled with a changelog or upgrade guide. "Starting in version 3.0 all our resources are prefixed to prevent any clashes. If you were overriding any strings all you need to do is add `kitesdk_` to the ones you were using."

**Comment by rpassis** [comment]
Unfortunately this has just caught us in a pretty bad way.

The current version of the Kite SDK has a French (and German) translated string of the SDK name (`app_name`) set and this has overridden our own `app_name`. 

Because these variables are not being prefixed, when our app was installed on devices configured with French language, the app name would come up as "Kite SDK". 

We will send a pull request for this and I trust you guys will merge it pretty quickly since it is a serious problem.

Thanks!
Rog

**Comment by sarahcyates** [comment]
Thanks for reporting this issue, it's even more important to make sure this is in as we are working on more language additions to the SDK as we speak. It unfortunately got missed as we didn't have anyone working on the SDK at that point in time. 

I'll let you know when this is live, which should be soon.

**Comment by sarahcyates** [comment]
Whoops, did not mean to close this one.

**Comment by sarahcyates** [comment]
Released in 5.8.7.

For now we've just prefixed all of the strings to use "kitesdk_" rather than every resource for now to lessen the number of updates everyone overriding would need to do. Will see how that goes for a bit, hopefully this issue is now resolved and you can use whatever string names you wish without the chance that odd translations will appear in your app.
