### ISSUE TITLE
Unable to validate payment. (Sandbox)

### ISSUE THREAD

**Issue by djones79** [OceanLabs/Android-Print-SDK#182]
Having issues trying to test an order in sandbox mode.  I'm using fake credit card data from [http://www.getcreditcardnumbers.com/](url).

I keep getting a dialog pop up saying: "Oops! We were unable to validate your payment. (P11)

Here's what I'm seeing in Logcat:
`07-07 16:12:33.350 3832-3832/com.dljonesapps.picstamatic I/StripeCreditCardFrag.: Successfully retrieved Stripe token: <com.stripe.android.model.Token@5501661 id=> JSON: {
                                                                                    "card": {
                                                                                      "address_city": null,
                                                                                      "address_country": null,
                                                                                      "address_line1": null,
                                                                                      "address_line2": null,
                                                                                      "address_state": null,
                                                                                      "address_zip": null,
                                                                                      "country": "GB",
                                                                                      "currency": null,
                                                                                      "cvc": null,
                                                                                      "exp_month": 9,
                                                                                      "exp_year": 2019,
                                                                                      "fingerprint": "6mkwmB7fgdTlZoBZ",
                                                                                      "last4": "3792",
                                                                                      "name": null,
                                                                                      "number": null,
                                                                                      "type": "Visa"
                                                                                    },
                                                                                    "created": "Jul 7, 2017 4:12:34 PM",
                                                                                    "id": "tok_1Ad3kc23ZjpKAxBPjMRV1WjQ",
                                                                                    "livemode": false,
                                                                                    "used": false
                                                                                  }`

**Comment by dbotha** [comment]
@djones79 You'll want to use a Stripe test credit card: https://stripe.com/docs/testing
