### ISSUE TITLE
Crash when selecting Facebook photos from FB Image source

### ISSUE THREAD

**Issue by IamJackppot** [OceanLabs/Android-Print-SDK#186]
When I click on an album, then select a single photo from the album, the app crashes with the following error:

`org.json.JSONException: No value for cover_photo`

Line `834` in `FacebookAgent.java`

Please take a look into it. 

Thank you.

**Comment by scsharp** [comment]
Thanks for opening an issue, we're currently working on a fix for this at the moment which is now in review, so hopefully this should work again in the next release.

**Comment by andreimacaveiu** [comment]
Could not replicate the issue.
