### ISSUE TITLE
Cannot import using gradle

### ISSUE THREAD

**Issue by stanislavmilev** [OceanLabs/Android-Print-SDK#29]
Added mavenCentral()
Added "compile 'ly.kite:kite-print-sdk:4.+'" to dependencies in build.gradle.
Gradle sync passes ok but when I try to use the KiteSDK object studio does not finds it.
.

**Comment by dbotha** [comment]
Hi @stanislavmilev - sorry for the delay, did you manage to get this working then? If not I'll try to reproduce.

**Comment by stanislavmilev** [comment]
Hello,
Thanks for the reply, I did fix the issue by updating to gradle-2.10-all.zip
