### ISSUE TITLE
Invalid request when paying with credit card in live mode

### ISSUE THREAD

**Issue by jguix** [OceanLabs/Android-Print-SDK#3]
I am having trouble with the payment means.

I've been able to put orders from the emulator, in test mode, using credit card. When I try the same from a mobile phone, I can never complete an order. I've tried with my app as well as with the sample app. I always get a popup with the message "Oops! Invalid request - see details". The scanner for credit cards doesn't work either. I did all my tests in test mode, never tried with the live mode.

I can provide full Logcat logs if you wish. Please find below a Logcat log with the warnings and errors that I found when trying to pay with a credit card. It states that "Connect to /65.50.196.201:443 timed out"

I tried with different smartphones, including a Motorola Moto G and a LG G3 S.

04-05 20:22:27.871      271-271/? D/SFPerfTracer﹕ layers: (6:12) (DimLayer: 0:81)\* (DimLayer: 0:8)\* (FocusedStackFrame: 1:846)\* (StatusBar: 3:7749) (NavigationBar: 0:3640) (com.android.systemui.ImageWallpaper: 0:400)\* (DimLayer: 1:777) (DimLayer: 0:183)\* (es.o3r3.postalprint/io.card.payment.DataEntryActivity: 0:119)\* (InputMethod: 1:68) (es.o3r3.postalprint/ly.kite.checkout.PaymentActivity: 20:31) (Processing: 245:265)
04-05 20:22:28.040    1022-1087/? D/WifiStateMachine﹕ handleMessage: E msg.what=151572
04-05 20:22:28.040    1022-1087/? D/WifiStateMachine﹕ processMsg: ConnectedState
04-05 20:22:28.040    1022-1087/? D/WifiStateMachine﹕ processMsg: L2ConnectedState
04-05 20:22:28.044    1022-1087/? D/WifiStateMachine﹕ handleMessage: X
04-05 20:22:28.668  29571-30792/es.o3r3.postalprint W/System.err﹕ org.apache.http.conn.ConnectTimeoutException: Connect to /65.50.196.201:443 timed out
04-05 20:22:28.676  29571-30792/es.o3r3.postalprint W/System.err﹕ at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
04-05 20:22:28.678  29571-30792/es.o3r3.postalprint W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
04-05 20:22:28.681  29571-30792/es.o3r3.postalprint W/System.err﹕ at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
04-05 20:22:28.682  29571-30792/es.o3r3.postalprint W/System.err﹕ at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
04-05 20:22:28.683  29571-30792/es.o3r3.postalprint W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:374)
04-05 20:22:28.684  29571-30792/es.o3r3.postalprint W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
04-05 20:22:28.686  29571-30792/es.o3r3.postalprint W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:498)
04-05 20:22:28.688  29571-30792/es.o3r3.postalprint W/System.err﹕ at io.card.payment.ak.run(Unknown Source)
04-05 20:22:28.689  29571-30792/es.o3r3.postalprint W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
04-05 20:22:28.689  29571-30792/es.o3r3.postalprint W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-05 20:22:28.690  29571-30792/es.o3r3.postalprint W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-05 20:22:28.691  29571-30792/es.o3r3.postalprint W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-05 20:22:28.692  29571-30792/es.o3r3.postalprint W/System.err﹕ at java.lang.Thread.run(Thread.java:841)

**Comment by dbotha** [comment]
This one's very odd. Could you explain a little more about the card scanner not working? I'm not quite sure about that socket timeout, it appears to be to an IP under PayPals control so I'll need to investigate. Unfortunately I'm not in the office today (it's a public holiday here in the UK) and don't have an Android phone to hand right now to test this but I'll investigate first thing tomorrow, sorry for the delay.

**Comment by dbotha** [comment]
@jguix upon investigation I _think_ this is because you're trying to enter a real credit card number into the sandbox/test environment although I could be wrong. Do you mind trying with a fake visa card generated from here and let me know what you see:

http://www.getcreditcardnumbers.com/

Also any more details on the card scanner issue? Does it just not show up for you? Does it crash?

**Comment by jguix** [comment]
I couldn't try with these fake cards because they miss the expiration date and CVV number.

I tried with fake VISA card numbers from other websites that do provide this data, but got the same result.

On the other hand, in the emulator (Genymotion) everything is working fine.
