### ISSUE TITLE
Documentation is incorrect?

### ISSUE THREAD

**Issue by IamJackppot** [OceanLabs/Android-Print-SDK#35]
I am setting up the Kite SDK based of this(the docs on creating an print order):

https://github.com/OceanLabs/Android-Print-SDK/blob/master/docs/create_print_order.md

I've included the following into the build.gradle and successfully synced the project:

`compile 'ly.kite:kite-print-sdk:4.+'`

Now, here's where the error occurs:

`KitePrintSDK.initialize("REPLACE_WITH_YOUR_API_KEY", KitePrintSDK.Environment.TEST, MyActivity.this);`
1. Apparently, the SDK is called `KiteSDK` instead of `KitePrintSDK`.
2. I get the following syntax errors whilst trying to initialize the SDK:

`KiteSDK.initialize("MY_API_KEY", KiteSDK.Environment.TEST, MainCollageActivity.this);`
"Cannot resolve method initialize(Java.lang.String, ?, com.app.test.test"

How can I initialize this SDK? Is the documentation wrong or am I missing something.

Thank you in advance.

**Comment by ghost** [comment]
Hi,

Thank you for your message. I must apologise for the documentation - it 
was something I inherited, and I hadn't realised that it was so out of 
date. I'll raise a card to get that particular document corrected, but 
in the mean time, probably the best place to start is with the sample app:

https://github.com/OceanLabs/Android-Print-SDK/blob/master/SampleApp/src/main/java/ly/kite/sample/MainActivity.java

It has different methods of jumping into the UI journey, but if you look 
at postcardJourney(), it shows you how to create your order manually and 
then go straight to the checkout.

Kind regards,

John

**Comment by IamJackppot** [comment]
Hi John

Thanks for the response.

Fortunately, I acknowledged the samples and I've successfully managed to set up my app accordingly.

-Jack
