### ISSUE TITLE
Login Failed when paying with Paypal

### ISSUE THREAD

**Issue by jguix** [OceanLabs/Android-Print-SDK#4]
Paypal doesn't work, it always says that I entered the wrong credentials, which I checked in Paypal.com. It happens to me in the emulator as well as in a real device, in sandbox mode.

The popup says "Login Failed. Invalid login information. Please try again."

Please find below the logcat log for this issue.

04-06 12:50:16.857      331-354/system_process I/ActivityManager﹕ Displayed es.o3r3.kiteprintapp/com.paypal.android.sdk.payments.PaymentMethodActivity: +73ms
04-06 12:50:18.029      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:50:36.457        58-58/? D/Genyd﹕ Received Set Clipboard
04-06 12:50:36.457        58-58/? D/Genymotion﹕ Received Set Clipboard
04-06 12:50:39.045      331-686/system_process I/ActivityManager﹕ START u0 {cmp=es.o3r3.kiteprintapp/com.paypal.android.sdk.payments.PaymentConfirmActivity (has extras)} from pid 1319
04-06 12:50:39.053      410-419/? W/genymotion_audio﹕ out_write() limiting sleep time 69659 to 23219
04-06 12:50:39.081      410-419/? W/genymotion_audio﹕ out_write() limiting sleep time 34829 to 23219
04-06 12:50:39.089      331-686/system_process D/dalvikvm﹕ GC_FOR_ALLOC freed 530K, 18% free 13876K/16740K, paused 4ms, total 5ms
04-06 12:50:39.097      331-686/system_process D/dalvikvm﹕ GC_FOR_ALLOC freed 748K, 20% free 13499K/16740K, paused 5ms, total 5ms
04-06 12:50:39.097      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:50:39.109    1319-1319/es.o3r3.kiteprintapp D/dalvikvm﹕ GC_FOR_ALLOC freed 470K, 10% free 11643K/12804K, paused 5ms, total 5ms
04-06 12:50:39.109    1319-1319/es.o3r3.kiteprintapp I/dalvikvm-heap﹕ Grow heap (frag case) to 11.580MB for 193128-byte allocation
04-06 12:50:39.113    1319-1328/es.o3r3.kiteprintapp D/dalvikvm﹕ GC_FOR_ALLOC freed <1K, 9% free 11831K/12996K, paused 4ms, total 5ms
04-06 12:50:39.125      331-534/system_process I/ActivityManager﹕ START u0 {cmp=es.o3r3.kiteprintapp/com.paypal.android.sdk.payments.LoginActivity (has extras)} from pid 1319
04-06 12:50:39.145    1319-1319/es.o3r3.kiteprintapp W/EGL_genymotion﹕ eglSurfaceAttrib not implemented
04-06 12:50:39.165      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:50:39.181      331-686/system_process W/InputMethodManagerService﹕ Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@52c58f60 (uid=10055 pid=1319)
04-06 12:50:39.189    1319-1319/es.o3r3.kiteprintapp D/dalvikvm﹕ GC_FOR_ALLOC freed 648K, 9% free 11922K/12996K, paused 6ms, total 6ms
04-06 12:50:39.189    1319-1319/es.o3r3.kiteprintapp I/dalvikvm-heap﹕ Grow heap (frag case) to 11.852MB for 193128-byte allocation
04-06 12:50:39.193    1319-1328/es.o3r3.kiteprintapp D/dalvikvm﹕ GC_FOR_ALLOC freed 3K, 9% free 12108K/13188K, paused 6ms, total 6ms
04-06 12:50:39.229    1319-1319/es.o3r3.kiteprintapp W/EGL_genymotion﹕ eglSurfaceAttrib not implemented
04-06 12:50:39.237    1319-1319/es.o3r3.kiteprintapp W/EGL_genymotion﹕ eglSurfaceAttrib not implemented
04-06 12:50:39.281      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:50:39.313      331-354/system_process I/ActivityManager﹕ Displayed es.o3r3.kiteprintapp/com.paypal.android.sdk.payments.LoginActivity: +163ms (total +213ms)
04-06 12:50:39.313      331-354/system_process I/ActivityManager﹕ Displayed es.o3r3.kiteprintapp/com.paypal.android.sdk.payments.PaymentConfirmActivity: +213ms
04-06 12:50:39.345      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:39.345      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:39.357      595-595/com.android.inputmethod.latin D/dalvikvm﹕ GC_FOR_ALLOC freed 279K, 4% free 9020K/9324K, paused 2ms, total 2ms
04-06 12:50:39.377      595-595/com.android.inputmethod.latin I/ResourceUtils﹕ Found default value: resource=sudden_jumping_touch_event_device_list build=[HARDWARE=vbox86 MODEL=Samsung Galaxy S3 - 4.3 - API 18 - 720x1280 BRAND=generic MANUFACTURER=Genymotion] default=false
04-06 12:50:39.377      595-595/com.android.inputmethod.latin I/ResourceUtils﹕ Found default value: resource=phantom_sudden_move_event_device_list build=[HARDWARE=vbox86 MODEL=Samsung Galaxy S3 - 4.3 - API 18 - 720x1280 BRAND=generic MANUFACTURER=Genymotion] default=false
04-06 12:50:39.381      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:39.385      595-595/com.android.inputmethod.latin I/ResourceUtils﹕ Found default value: resource=keyboard_heights build=[HARDWARE=vbox86 MODEL=Samsung Galaxy S3 - 4.3 - API 18 - 720x1280 BRAND=generic MANUFACTURER=Genymotion] default=
04-06 12:50:39.405      595-595/com.android.inputmethod.latin D/dalvikvm﹕ GC_FOR_ALLOC freed 83K, 2% free 9442K/9552K, paused 4ms, total 4ms
04-06 12:50:39.437      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:39.453      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:39.477      595-595/com.android.inputmethod.latin D/libEGL﹕ loaded /system/lib/egl/libEGL_genymotion.so
04-06 12:50:39.477      595-595/com.android.inputmethod.latin D/﹕ HostConnection::get() New Host Connection established 0xb878e0f8, tid 595
04-06 12:50:39.485      595-595/com.android.inputmethod.latin D/libEGL﹕ loaded /system/lib/egl/libGLESv1_CM_genymotion.so
04-06 12:50:39.485      595-595/com.android.inputmethod.latin D/libEGL﹕ loaded /system/lib/egl/libGLESv2_genymotion.so
04-06 12:50:39.497      595-595/com.android.inputmethod.latin W/EGL_genymotion﹕ eglSurfaceAttrib not implemented
04-06 12:50:39.497      595-595/com.android.inputmethod.latin E/OpenGLRenderer﹕ Getting MAX_TEXTURE_SIZE from GradienCache
04-06 12:50:39.501      595-595/com.android.inputmethod.latin E/OpenGLRenderer﹕ Getting MAX_TEXTURE_SIZE from Caches::initConstraints()
04-06 12:50:39.501      595-595/com.android.inputmethod.latin D/OpenGLRenderer﹕ Enabling debug mode 0
04-06 12:50:39.533      595-595/com.android.inputmethod.latin W/EGL_genymotion﹕ eglSurfaceAttrib not implemented
04-06 12:50:39.545      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:50:40.201    1319-1382/es.o3r3.kiteprintapp D/dalvikvm﹕ GC_FOR_ALLOC freed 840K, 7% free 12370K/13240K, paused 4ms, total 5ms
04-06 12:50:40.445      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:50:47.833      595-595/com.android.inputmethod.latin D/dalvikvm﹕ GC_FOR_ALLOC freed 194K, 3% free 9736K/9956K, paused 2ms, total 3ms
04-06 12:50:47.837      595-595/com.android.inputmethod.latin I/dalvikvm-heap﹕ Grow heap (frag case) to 11.054MB for 1598412-byte allocation
04-06 12:50:47.837      595-595/com.android.inputmethod.latin D/dalvikvm﹕ GC_FOR_ALLOC freed 15K, 3% free 11282K/11520K, paused 2ms, total 2ms
04-06 12:50:52.429      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:52.429      410-419/? W/genymotion_audio﹕ out_write() limiting sleep time 69659 to 23219
04-06 12:50:52.453      410-419/? W/genymotion_audio﹕ out_write() limiting sleep time 34829 to 23219
04-06 12:50:52.461      331-346/system_process D/dalvikvm﹕ GC_FOR_ALLOC freed 1476K, 22% free 13202K/16740K, paused 9ms, total 10ms
04-06 12:50:52.461      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:52.461      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:52.461      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:52.461      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:50:52.501      410-419/? W/genymotion_audio﹕ out_write() limiting sleep time 34828 to 23219
04-06 12:50:53.209      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:50:58.305      410-419/? W/genymotion_audio﹕ out_write() limiting sleep time 69659 to 23219
04-06 12:50:58.325      410-419/? W/genymotion_audio﹕ out_write() limiting sleep time 34829 to 23219
04-06 12:50:58.329    1319-1319/es.o3r3.kiteprintapp W/EGL_genymotion﹕ eglSurfaceAttrib not implemented
04-06 12:50:58.965      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:51:00.949      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:51:02.961      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:51:03.861    1319-1380/es.o3r3.kiteprintapp E/RequestError﹕ , Mobile Login failed.
04-06 12:51:03.861    1319-1319/es.o3r3.kiteprintapp E/PayPalService﹕ 10803
04-06 12:51:03.869    1319-1319/es.o3r3.kiteprintapp E/LoginActivity﹕ login error: 10803
04-06 12:51:03.873      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:03.897    1319-1319/es.o3r3.kiteprintapp W/EGL_genymotion﹕ eglSurfaceAttrib not implemented
04-06 12:51:03.897    1319-1319/es.o3r3.kiteprintapp W/IInputConnectionWrapper﹕ getTextBeforeCursor on inactive InputConnection
04-06 12:51:03.913    1319-1319/es.o3r3.kiteprintapp W/IInputConnectionWrapper﹕ getTextBeforeCursor on inactive InputConnection
04-06 12:51:03.913      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:03.913      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:03.913      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:03.913      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:03.913      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:03.925      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:03.925      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:03.925      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:03.925      595-595/com.android.inputmethod.latin V/InputMethodService﹕ onEvaluateInputViewShown: config.hardKeyboardHidden = 2
04-06 12:51:04.177      331-466/system_process D/MobileDataStateTracker﹕ default: setPolicyDataEnable(enabled=true)
04-06 12:51:04.473    1319-1380/es.o3r3.kiteprintapp D/dalvikvm﹕ GC_FOR_ALLOC freed 1146K, 9% free 12419K/13592K, paused 5ms, total 6ms

**Comment by dbotha** [comment]
@jguix To use PayPal in sandbox mode you need to signup as a PayPal developer and get yourself a PayPal sandbox account (they won't let you use a live one in the sandbox environment). You can start here: https://developer.paypal.com/webapps/developer/applications/accounts

If you run into any trouble let me know and I'll try help more :)

**Comment by dbotha** [comment]
Oh let me know if that works for you and I'll close this issue if so.

**Comment by jguix** [comment]
It worked!

Thanks for your help.

**Comment by dbotha** [comment]
No problem :)
