### ISSUE TITLE
POSTCARD.getDefaultTemplate() returns wrong value

### ISSUE THREAD

**Issue by jguix** [OceanLabs/Android-Print-SDK#5]
Using the code from the sample app gives an error, since ProductType.POSTCARD.getDefaultTemplate() returns "id_postcard", which seems to be wrong.

```
printOrder.addPrintJob(PrintJob.createPostcardPrintJob(
    ProductType.POSTCARD.getDefaultTemplate(), assets.get(0), "Hello World!", 
    Address.getKiteTeamAddress()));
```

What works for me is setting the template to "postcard".

```
PrintJob printJob = PrintJob.createPostcardPrintJob("postcard", assets.get(0), content, address);
```

**Comment by dbotha** [comment]
@jguix good catch, this is my oversight. Thanks for pointing it out! We're radically overhauling the Android SDK as I type this to bring it inline with where iOS currently is -- so lots of new products, beautiful product selection, image editing and checkout screens, etc. It should land later this month...

**Comment by sirvon** [comment]
any date/expectation on the new Android SDK?

**Comment by dbotha** [comment]
Hi @sirvon -- we've just this week brought on a full time Android developer to assist with our workload. I suspect it should be on par with iOS in around 1 month. That said the only thing missing in comparison is the UI journeys. If you're building those yourself the SDK is fit for your purposes today!

**Comment by sirvon** [comment]
thx for that quick reponse...if I were to use one of the more recently updated branches will I run into majot troubles? or even that pull request....

**Comment by dbotha** [comment]
Hi @sirvon -- you're welcome to try but I'd probably hold off for a couple of weeks.
