### ISSUE TITLE
Errors whilst adding SDK to app

### ISSUE THREAD

**Issue by IamJackppot** [OceanLabs/Android-Print-SDK#53]
When trying to add the KiteSDK to my project in Android Studio by downloading it and doing it manually (I would like to customize the SDK to my liking), I run into an issue. 

The issue is that when adding the SDK as module to my app, the SDK for some reason doesn't recognize the app compat library.

I've tried removing all app compat dependencies in my app so there's no confilct, but, the SDK still doesn't recognize that app compat library that's required.

Is  there anything I should know before adding the SDK manually to my app? 

Thanks.

**Comment by ghost** [comment]
The SDK module already has a dependency on the AppCompat library 
included in its build.gradle file:

compile 'com.android.support:appcompat-v7:23.4.0'

When you say it doesn't recognise it, what error are you getting? Are 
you trying to include it again elsewhere?

**Comment by IamJackppot** [comment]
I have now got it fixed. I'm not sure what the problem was but I changed a lot of things regarding the gradle version I was using etc. Thanks anyway.
