### ISSUE TITLE
startShopping() requires ArrayList, ideally it should accept a List

### ISSUE THREAD

**Issue by clockworkant** [OceanLabs/Android-Print-SDK#64]
Loosen the type of the parameter for assets in the startShopping so that a List<Assets> may be used.

Feel free to disregard this if you feel there is a good reason to only accept ArrayLists 😄

**Comment by ghost** [comment]
The asset list is added as an extra to an intent, which is why it needs 
to be an ArrayList. If it were loosened to a List, it would need to be 
cast or converted, which is pretty trivial to do in the app anyway.

**Comment by clockworkant** [comment]
I understand. Interesting. I'd still prefer it to have a looser type and have the api handle conversion however I leave the api design entirely upto you.

Thanks for explaining the necessity for the stronger typing.
