### ISSUE TITLE
Expose ImageSelectionAdaptor.mAssetCount on a method for testing

### ISSUE THREAD

**Issue by clockworkant** [OceanLabs/Android-Print-SDK#65]
Could you please make a getter for mAssetCount so that I can verify how many assets are in the ImageSelectionAdaptor. Currently getItemCount will return a value in order to render a full list with placeholder tiles.

**Comment by ghost** [comment]
I can certainly add this. Can I ask why you want it? Are you doing something exotic, like re-writing the screen yourself but using the existing components?

**Comment by clockworkant** [comment]
Nothing that exotic! I'm using the existing component however I am writing an integration test with espresso to ensure that a user can go end to end. I wanted to have a ui test that ensure that the ImageSource is working correctly and adding to the shopping cart.

**Comment by ghost** [comment]
OK - an updated SDK is available on Maven, which includes access to the 
asset count.
