### ISSUE TITLE
Filename too long when startingShopping with very long url

### ISSUE THREAD

**Issue by clockworkant** [OceanLabs/Android-Print-SDK#68]
I'm calling startShopping an asset that has a url that is 391 characters long. It is very long as it has GET parameters holding signatures to access the content.

The stack trace reports:

`10-03 10:43:27.090 4413-4554/? E/FileDownloader: Unable to download to file
                                                 java.io.IOException: open failed: ENAMETOOLONG (File name too long)
                                                     at java.io.File.createNewFile(File.java:939)
                                                     at java.io.File.createTempFile(File.java:1004)
                                                     at java.io.File.createTempFile(File.java:961)
                                                     at ly.kite.util.FileDownloader.download(FileDownloader.java:144)
                                                     at ly.kite.util.FileDownloader$DownloaderTask.doInBackground(FileDownloader.java:345)
                                                     at ly.kite.util.FileDownloader$DownloaderTask.doInBackground(FileDownloader.java:308)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at java.lang.Thread.run(Thread.java:818)`

I haven't looked into the details too much for a solution but perhaps the filename generation could strip query parameters to shorten it before hand.

**Comment by ghost** [comment]
Would it be possible to send me the URL that you're using, so I can look 
at it? Stripping the query parameters would work if different parameters 
didn't result in a different image being returned (in the same session), 
since it's used for caching.

**Comment by clockworkant** [comment]
@JLKite 

I/FileDownloader: Downloading: https://d3qdv9ui78zmx0.cloudfront.net/b6a6bb67-49f9-468a-9d4a-2765eabbccbd/c97402ff-956f-4137-8560-6d3cc14825e0/706_c97402ff-956f-4137-8560-6d3cc14825e0.jpg?Expires=1478081713&Signature=dYGB8Llw4Xs3UOYKpT2z5fnIogMCGhwaCQjFpIyDN6gwCAZPk1uxezQyRio2kXhvplkIf9LcJdtIeTmTpCxjyfBQ72dl2purR0sj5GwdAavVZeS7WwdXsPLWSsRAysbhk4hrC3LNBSO1YDT9n9tnJmXx~m-PYEfNu8J-fBPLpbo_&Key-Pair-Id=APKAJHWMISAIRUOD7MQQ -> /data/user/0/com.someapp.debug/cache/session_asset/https___d3qdv9ui78zmx0_cloudfront_net_b6a6bb67_49f9_468a_9d4a_2765eabbccbd_c97402ff_956f_4137_8560_6d3cc14825e0_706_c97402ff_956f_4137_8560_6d3cc14825e0_jpg_Expires_1478081713_Signature_dYGB8Llw4Xs3UOYKpT2z5fnIogMCGhwaCQjFpIyDN6gwCAZPk1uxezQyRio2kXhvplkIf9LcJdtIeTmTpCxjyfBQ72dl2purR0sj5GwdAavVZeS7WwdXsPLWSsRAysbhk4hrC3LNBSO1YDT9n9tnJmXx_m_PYEfNu8J_fBPLpbo__Key_Pair_Id_APKAJHWMISAIRUOD7MQQ

**Comment by ghost** [comment]
I've put in a fix for this and uploaded it to Maven. Version 5.5.2 
should be available in a couple of hours.

**Comment by clockworkant** [comment]
@JLKite the update is live however I am getting the following issue:

`> Could not find Android-Print-SDK:FacebookPhotoPicker:unspecified.
 Searched in the following locations:
     https://repo1.maven.org/maven2/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.pom
     https://repo1.maven.org/maven2/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.jar
     https://jcenter.bintray.com/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.pom
     https://jcenter.bintray.com/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.jar
     file:/.../libs/FacebookPhotoPicker-unspecified.jar
     file:/.../libs/FacebookPhotoPicker.jar
     file:/Users/.../Library/Android/sdk/extras/android/m2repository/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.pom
     file:/Users/.../Library/Android/sdk/extras/android/m2repository/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.jar
     file:/Users/.../Library/Android/sdk/extras/google/m2repository/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.pom
     file:/Users/.../Library/Android/sdk/extras/google/m2repository/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.jar
     file:/Users/.../Library/Android/sdk/extras/m2repository/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.pom
     file:/Users/.../Library/Android/sdk/extras/m2repository/Android-Print-SDK/FacebookPhotoPicker/unspecified/FacebookPhotoPicker-unspecified.jar
 Required by:
     PRODUCT-android:PRODUCT:unspecified > ly.kite:kite-print-sdk:5.5.2`

**Comment by ghost** [comment]
Sorry for the delay in responding - it took me a while to find out what 
was going on, then I had to release a load of new libraries, and each 
one took a couple of hours before I could go onto the next one.

Anyway, give it a try now - version 5.5.4. It works for me when I use 
the Maven library building the sample app.

**Comment by clockworkant** [comment]
@JLKite the maven repo's are now working however I've noticed a few issues:
1. The min api has crept up to 15 from 14. (bit of a pain on our side as we support a min of 14!
2. Facebook sdk is now a dependency and we are using an older version of the sdk and causes a conflict.

Is there any way to decouple the facebook requirement to a separate optional module rather than have it inside of the main print sdk?

I apologise for generating so much work for you!

**Comment by clockworkant** [comment]
I've managed to retain a min api level of 14 by doing the following which could be dangerous:
In my androidmanfiest.xml I've added
`<uses-sdk tools:overrideLibrary="ly.kite, ly.kite.facebookphotopicker, ly.kite.imagepicker" />`

To avoid the facebook library clashing with our own I've used: 
`compile ('ly.kite:kite-print-sdk:5.5.4'){
        exclude group: 'com.facebook.android', module: 'facebook-android-sdk';
}`

I'm fairly uncomfortable with this being a solution as if the kite sdk has anything from api 15 it will probably explode our application and I'll only discover this at run time.

In good news, the long file name fix is successful!!

**Comment by ghost** [comment]
Well if you want to remove the Facebook stuff in a more robust way - you 
could always build your app using the source from GitHub, rather than 
using the Maven library.

I'm currently waiting to hear back about whether Kite wants to remove it 
and make it optional.

**Comment by clockworkant** [comment]
This is fixed as of kite 5.6.3 (facebook and version clashes no longer happen either)

Great work, thanks!

**Comment by KamalNishad** [comment]
java.io.FileNotFoundException: /data/user/0/gov.chips.cgstate.cgrofra/app_ROFRA_FS/[, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , Photo1670324106.png, Photo1671105090.jpg, , Photo1671541374.jpg]: open failed: ENAMETOOLONG (File name too long)       .................???????


getting this error when handle to download server files but manually try to download 2 3 images it works fine what should i do..?
